# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Oct 16 11:57:49 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 550)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pb_Arribo = QtGui.QPushButton(self.centralwidget)
        self.pb_Arribo.setGeometry(QtCore.QRect(100, 480, 75, 24))
        self.pb_Arribo.setObjectName(_fromUtf8("pb_Arribo"))
        self.pb_Eliminar = QtGui.QPushButton(self.centralwidget)
        self.pb_Eliminar.setGeometry(QtCore.QRect(285, 480, 75, 24))
        self.pb_Eliminar.setAutoDefault(False)
        self.pb_Eliminar.setFlat(False)
        self.pb_Eliminar.setObjectName(_fromUtf8("pb_Eliminar"))
        self.pb_Salida = QtGui.QPushButton(self.centralwidget)
        self.pb_Salida.setGeometry(QtCore.QRect(15, 480, 75, 24))
        self.pb_Salida.setObjectName(_fromUtf8("pb_Salida"))
        self.pb_Salir = QtGui.QPushButton(self.centralwidget)
        self.pb_Salir.setGeometry(QtCore.QRect(710, 480, 75, 24))
        self.pb_Salir.setObjectName(_fromUtf8("pb_Salir"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(11, 50, 780, 410))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPaseosActivos = QtGui.QWidget()
        self.tabPaseosActivos.setObjectName(_fromUtf8("tabPaseosActivos"))
        self.tableWidget = QtGui.QTableWidget(self.tabPaseosActivos)
        self.tableWidget.setGeometry(QtCore.QRect(-1, -1, 780, 410))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.tabPaseosActivos, _fromUtf8(""))
        self.tabPaseosProgramados = QtGui.QWidget()
        self.tabPaseosProgramados.setObjectName(_fromUtf8("tabPaseosProgramados"))
        self.tableWidget_2 = QtGui.QTableWidget(self.tabPaseosProgramados)
        self.tableWidget_2.setGeometry(QtCore.QRect(-1, -1, 780, 410))
        self.tableWidget_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(150)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.tabPaseosProgramados, _fromUtf8(""))
        self.pb_Nuevo = QtGui.QPushButton(self.centralwidget)
        self.pb_Nuevo.setGeometry(QtCore.QRect(200, 480, 75, 24))
        self.pb_Nuevo.setObjectName(_fromUtf8("pb_Nuevo"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuClientes = QtGui.QMenu(self.menubar)
        self.menuClientes.setObjectName(_fromUtf8("menuClientes"))
        self.menuMascotas = QtGui.QMenu(self.menubar)
        self.menuMascotas.setObjectName(_fromUtf8("menuMascotas"))
        self.menuPaseadores = QtGui.QMenu(self.menubar)
        self.menuPaseadores.setObjectName(_fromUtf8("menuPaseadores"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAltaCliente = QtGui.QAction(MainWindow)
        self.actionAltaCliente.setObjectName(_fromUtf8("actionAltaCliente"))
        self.actionModificarCliente = QtGui.QAction(MainWindow)
        self.actionModificarCliente.setObjectName(_fromUtf8("actionModificarCliente"))
        self.actionListadoCliente = QtGui.QAction(MainWindow)
        self.actionListadoCliente.setObjectName(_fromUtf8("actionListadoCliente"))
        self.actionAltaMascota = QtGui.QAction(MainWindow)
        self.actionAltaMascota.setObjectName(_fromUtf8("actionAltaMascota"))
        self.actionModificarMascota = QtGui.QAction(MainWindow)
        self.actionModificarMascota.setObjectName(_fromUtf8("actionModificarMascota"))
        self.actionListadoMascota = QtGui.QAction(MainWindow)
        self.actionListadoMascota.setObjectName(_fromUtf8("actionListadoMascota"))
        self.actionAltaPaseador = QtGui.QAction(MainWindow)
        self.actionAltaPaseador.setObjectName(_fromUtf8("actionAltaPaseador"))
        self.actionModificarPaseador = QtGui.QAction(MainWindow)
        self.actionModificarPaseador.setObjectName(_fromUtf8("actionModificarPaseador"))
        self.actionListadoPaseador = QtGui.QAction(MainWindow)
        self.actionListadoPaseador.setObjectName(_fromUtf8("actionListadoPaseador"))
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.menuMenu.addAction(self.actionSalir)
        self.menuClientes.addAction(self.actionAltaCliente)
        self.menuClientes.addAction(self.actionModificarCliente)
        self.menuClientes.addSeparator()
        self.menuClientes.addAction(self.actionListadoCliente)
        self.menuMascotas.addAction(self.actionAltaMascota)
        self.menuMascotas.addAction(self.actionModificarMascota)
        self.menuMascotas.addSeparator()
        self.menuMascotas.addAction(self.actionListadoMascota)
        self.menuPaseadores.addAction(self.actionAltaPaseador)
        self.menuPaseadores.addAction(self.actionModificarPaseador)
        self.menuPaseadores.addSeparator()
        self.menuPaseadores.addAction(self.actionListadoPaseador)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuMascotas.menuAction())
        self.menubar.addAction(self.menuPaseadores.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pb_Salir, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Paseadores", None))
        self.pb_Arribo.setText(_translate("MainWindow", "Arribo", None))
        self.pb_Eliminar.setText(_translate("MainWindow", "Eliminar", None))
        self.pb_Salida.setText(_translate("MainWindow", "Salida", None))
        self.pb_Salir.setText(_translate("MainWindow", "Salir", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Salida", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Arribo", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Paseador", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPaseosActivos), _translate("MainWindow", "Paseadores Activos", None))
        self.tableWidget_2.setSortingEnabled(True)
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Salida", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Arribo", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Paseador", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPaseosProgramados), _translate("MainWindow", "Paseos Programados", None))
        self.pb_Nuevo.setText(_translate("MainWindow", "Nuevo", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menuClientes.setTitle(_translate("MainWindow", "Clientes", None))
        self.menuMascotas.setTitle(_translate("MainWindow", "Mascotas", None))
        self.menuPaseadores.setTitle(_translate("MainWindow", "Paseadores", None))
        self.actionAltaCliente.setText(_translate("MainWindow", "Alta", None))
        self.actionAltaCliente.setShortcut(_translate("MainWindow", "F1", None))
        self.actionModificarCliente.setText(_translate("MainWindow", "Modificacion", None))
        self.actionModificarCliente.setShortcut(_translate("MainWindow", "F4", None))
        self.actionListadoCliente.setText(_translate("MainWindow", "Listado", None))
        self.actionListadoCliente.setShortcut(_translate("MainWindow", "F7", None))
        self.actionAltaMascota.setText(_translate("MainWindow", "Alta", None))
        self.actionAltaMascota.setShortcut(_translate("MainWindow", "F2", None))
        self.actionModificarMascota.setText(_translate("MainWindow", "Modificacion", None))
        self.actionModificarMascota.setShortcut(_translate("MainWindow", "F5", None))
        self.actionListadoMascota.setText(_translate("MainWindow", "Listado", None))
        self.actionListadoMascota.setShortcut(_translate("MainWindow", "F8", None))
        self.actionAltaPaseador.setText(_translate("MainWindow", "Alta", None))
        self.actionAltaPaseador.setShortcut(_translate("MainWindow", "F3", None))
        self.actionModificarPaseador.setText(_translate("MainWindow", "Modificacion", None))
        self.actionModificarPaseador.setShortcut(_translate("MainWindow", "F6", None))
        self.actionListadoPaseador.setText(_translate("MainWindow", "Listado", None))
        self.actionListadoPaseador.setShortcut(_translate("MainWindow", "F9", None))
        self.actionSalir.setText(_translate("MainWindow", "Salir", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

