# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Oct 30 15:56:14 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 550)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pb_Arribo = QtGui.QPushButton(self.centralwidget)
        self.pb_Arribo.setGeometry(QtCore.QRect(100, 480, 75, 24))
        self.pb_Arribo.setObjectName(_fromUtf8("pb_Arribo"))
        self.pb_Salida = QtGui.QPushButton(self.centralwidget)
        self.pb_Salida.setGeometry(QtCore.QRect(15, 480, 75, 24))
        self.pb_Salida.setObjectName(_fromUtf8("pb_Salida"))
        self.pb_Salir = QtGui.QPushButton(self.centralwidget)
        self.pb_Salir.setGeometry(QtCore.QRect(710, 480, 75, 24))
        self.pb_Salir.setObjectName(_fromUtf8("pb_Salir"))
        self.tab_Paseos = QtGui.QTabWidget(self.centralwidget)
        self.tab_Paseos.setGeometry(QtCore.QRect(11, 50, 780, 410))
        self.tab_Paseos.setTabPosition(QtGui.QTabWidget.North)
        self.tab_Paseos.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_Paseos.setObjectName(_fromUtf8("tab_Paseos"))
        self.tabPaseosActivos = QtGui.QWidget()
        self.tabPaseosActivos.setObjectName(_fromUtf8("tabPaseosActivos"))
        self.table_Activos = QtGui.QTableWidget(self.tabPaseosActivos)
        self.table_Activos.setGeometry(QtCore.QRect(-1, -1, 780, 410))
        self.table_Activos.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_Activos.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.table_Activos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_Activos.setObjectName(_fromUtf8("table_Activos"))
        self.table_Activos.setColumnCount(4)
        self.table_Activos.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_Activos.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_Activos.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_Activos.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_Activos.setHorizontalHeaderItem(3, item)
        self.table_Activos.horizontalHeader().setCascadingSectionResizes(False)
        self.table_Activos.horizontalHeader().setDefaultSectionSize(250)
        self.table_Activos.horizontalHeader().setMinimumSectionSize(200)
        self.table_Activos.horizontalHeader().setSortIndicatorShown(True)
        self.table_Activos.horizontalHeader().setStretchLastSection(True)
        self.table_Activos.verticalHeader().setVisible(False)
        self.tab_Paseos.addTab(self.tabPaseosActivos, _fromUtf8(""))
        self.tabHistorialPaseos = QtGui.QWidget()
        self.tabHistorialPaseos.setObjectName(_fromUtf8("tabHistorialPaseos"))
        self.table_Historial = QtGui.QTableWidget(self.tabHistorialPaseos)
        self.table_Historial.setGeometry(QtCore.QRect(-1, -1, 780, 410))
        self.table_Historial.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_Historial.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.table_Historial.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_Historial.setObjectName(_fromUtf8("table_Historial"))
        self.table_Historial.setColumnCount(5)
        self.table_Historial.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_Historial.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_Historial.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_Historial.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_Historial.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_Historial.setHorizontalHeaderItem(4, item)
        self.table_Historial.horizontalHeader().setCascadingSectionResizes(False)
        self.table_Historial.horizontalHeader().setDefaultSectionSize(200)
        self.table_Historial.horizontalHeader().setMinimumSectionSize(150)
        self.table_Historial.horizontalHeader().setSortIndicatorShown(True)
        self.table_Historial.horizontalHeader().setStretchLastSection(True)
        self.table_Historial.verticalHeader().setVisible(False)
        self.tab_Paseos.addTab(self.tabHistorialPaseos, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuClientes = QtGui.QMenu(self.menubar)
        self.menuClientes.setObjectName(_fromUtf8("menuClientes"))
        self.menuMascotas = QtGui.QMenu(self.menubar)
        self.menuMascotas.setObjectName(_fromUtf8("menuMascotas"))
        self.menuPaseadores = QtGui.QMenu(self.menubar)
        self.menuPaseadores.setObjectName(_fromUtf8("menuPaseadores"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAltaCliente = QtGui.QAction(MainWindow)
        self.actionAltaCliente.setObjectName(_fromUtf8("actionAltaCliente"))
        self.actionListadoCliente = QtGui.QAction(MainWindow)
        self.actionListadoCliente.setObjectName(_fromUtf8("actionListadoCliente"))
        self.actionAltaMascota = QtGui.QAction(MainWindow)
        self.actionAltaMascota.setObjectName(_fromUtf8("actionAltaMascota"))
        self.actionListadoMascota = QtGui.QAction(MainWindow)
        self.actionListadoMascota.setObjectName(_fromUtf8("actionListadoMascota"))
        self.actionAltaPaseador = QtGui.QAction(MainWindow)
        self.actionAltaPaseador.setObjectName(_fromUtf8("actionAltaPaseador"))
        self.actionListadoPaseador = QtGui.QAction(MainWindow)
        self.actionListadoPaseador.setObjectName(_fromUtf8("actionListadoPaseador"))
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionConfiguracion = QtGui.QAction(MainWindow)
        self.actionConfiguracion.setObjectName(_fromUtf8("actionConfiguracion"))
        self.menuMenu.addAction(self.actionConfiguracion)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionSalir)
        self.menuClientes.addAction(self.actionAltaCliente)
        self.menuClientes.addSeparator()
        self.menuClientes.addAction(self.actionListadoCliente)
        self.menuMascotas.addAction(self.actionAltaMascota)
        self.menuMascotas.addSeparator()
        self.menuMascotas.addAction(self.actionListadoMascota)
        self.menuPaseadores.addAction(self.actionAltaPaseador)
        self.menuPaseadores.addSeparator()
        self.menuPaseadores.addAction(self.actionListadoPaseador)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuMascotas.menuAction())
        self.menubar.addAction(self.menuPaseadores.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_Paseos.setCurrentIndex(0)
        QtCore.QObject.connect(self.pb_Salir, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.actionSalir, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Paseadores", None))
        self.pb_Arribo.setText(_translate("MainWindow", "Arribo", None))
        self.pb_Salida.setText(_translate("MainWindow", "Salida", None))
        self.pb_Salir.setText(_translate("MainWindow", "Salir", None))
        self.table_Activos.setSortingEnabled(True)
        item = self.table_Activos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Salida", None))
        item = self.table_Activos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Arribo", None))
        item = self.table_Activos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Paseador", None))
        item = self.table_Activos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Codigo", None))
        self.tab_Paseos.setTabText(self.tab_Paseos.indexOf(self.tabPaseosActivos), _translate("MainWindow", "Paseadores Activos", None))
        self.table_Historial.setSortingEnabled(True)
        item = self.table_Historial.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha", None))
        item = self.table_Historial.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Salida", None))
        item = self.table_Historial.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Arribo", None))
        item = self.table_Historial.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Paseador", None))
        item = self.table_Historial.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Codigo", None))
        self.tab_Paseos.setTabText(self.tab_Paseos.indexOf(self.tabHistorialPaseos), _translate("MainWindow", "Historial Paseos", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menuClientes.setTitle(_translate("MainWindow", "Clientes", None))
        self.menuMascotas.setTitle(_translate("MainWindow", "Mascotas", None))
        self.menuPaseadores.setTitle(_translate("MainWindow", "Paseadores", None))
        self.actionAltaCliente.setText(_translate("MainWindow", "Alta", None))
        self.actionAltaCliente.setShortcut(_translate("MainWindow", "F1", None))
        self.actionListadoCliente.setText(_translate("MainWindow", "Listado", None))
        self.actionListadoCliente.setShortcut(_translate("MainWindow", "F4", None))
        self.actionAltaMascota.setText(_translate("MainWindow", "Alta", None))
        self.actionAltaMascota.setShortcut(_translate("MainWindow", "F2", None))
        self.actionListadoMascota.setText(_translate("MainWindow", "Listado", None))
        self.actionListadoMascota.setShortcut(_translate("MainWindow", "F5", None))
        self.actionAltaPaseador.setText(_translate("MainWindow", "Alta", None))
        self.actionAltaPaseador.setShortcut(_translate("MainWindow", "F3", None))
        self.actionListadoPaseador.setText(_translate("MainWindow", "Listado", None))
        self.actionListadoPaseador.setShortcut(_translate("MainWindow", "F6", None))
        self.actionSalir.setText(_translate("MainWindow", "Salir", None))
        self.actionSalir.setShortcut(_translate("MainWindow", "F9", None))
        self.actionConfiguracion.setText(_translate("MainWindow", "Configuracion", None))
        self.actionConfiguracion.setShortcut(_translate("MainWindow", "F7", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

